### ISSUE TITLE
Fix DE spam killing capital planets.

### ISSUE THREAD

**Issue by GoaFan77** [GoaFan77/Enhanced4XModRepo#21]
The Deliverance Engine, if spammed enough on an enemy planet, can force a culture loss with nothing the target player can do. This is particularly toxic with Homeworld Victory.

Option 1: Change the Deliverance Engine's allegiance Debuff to not reapply until the other effects of the DE have expired. This should help prevent focus firing DE shots from taking out planets.

Option 2: Change the allegiance debuff to not affect capital planets.

**Comment by DesaraINT** [comment]
I'm very much in favor of option 2 as that allows the DE to have that niche usage without the threat of auto-winning a capital victory as no other faction really has that with their super weapon

**Comment by CaesarsLegion** [comment]
Problem with Option 2, is that it does not prevent culture bombing surrounding territory to nuke the homeworld still.
I would suggest that actually, the culture 'bomb' effect be reduced so that it should be used in conjunction with front-line culture aggression for pushing a frontline, and in the backline, have an increased allegiance debuff to be used as an economic weapon with a reasonable duration.

**Comment by GoaFan77** [comment]
> Problem with Option 2, is that it does not prevent culture bombing surrounding territory to nuke the homeworld still. I would suggest that actually, the culture 'bomb' effect be reduced so that it should be used in conjunction with front-line culture aggression for pushing a frontline, and in the backline, have an increased allegiance debuff to be used as an economic weapon with a reasonable duration.

Have you actually seen this happen? If you have culture of your own, it should somewhat heal the allegiance damage from just the culture effect. I've not usually seen this work unless your culture was already on the verge of overtaking the enemy.

**Comment by CaesarsLegion** [comment]
It will requires the consistent staggered effect of 2-3 cannons, but yes, it can be done.

**Comment by GoaFan77** [comment]
Added a cooldown on how often the 10% allegiance penalty can occur. Will close for now, may revisit after further testing.
