### ISSUE TITLE
TEC Homeworld Culture Bug

### ISSUE THREAD

**Issue by GoaFan77** [GoaFan77/Enhanced4XModRepo#3]
TEC Loyals' homeworld is the only one to not auto-spread culture (due to their command center having 'Ability_E4X_InvincibleEntityTechLoyals' in place of 'Ability_E4X_CommandCenter'.)

**Comment by bigbantha** [comment]
#6 Fixed by adding 'Buff_E4X_CommandCenterCulture' as an instant action.
